MarcelaLopez3/ProyectoEmenic

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
Modificación de rutas css. Queda pendiente el uso de dropdownlist cliente.
> Modificación de rutas en página Master

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/ClientesRegistro.aspx
Modificación de redireccionamiento y uso de dropdown en menú 09:58pm
> Modificación de redireccionamiento y uso de dropdown en menú

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroJuridicos.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroNaturales.aspx.designer.cs
Arreglé el formulario de personas naturales y juridicas, y master(solo nombres)
> Arreglando formularios de naturales y juridicos

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
> Quitando referencia

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
> Cambios personas

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroJuridicos.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/RegistroNaturales.aspx.designer.cs
> Actualizando formularios con las banderas

- ProyectoASPEmenic/ProyectoASPEmenic/App_Code/Conexion.cs
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
> Terminando CRUD Naturales

- ProyectoASPEmenic/ProyectoASPEmenic/Default.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Default.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Default.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master.cs
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Web.config
No se podrá ingresar a módulos internos si no ha iniciado sesión
> Agregar funcionalidad al login y a la sesión de usuario

- ProyectoASPEmenic/ProyectoASPEmenic/Default.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Default.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Default.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Login.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Login.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Login.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
Cambio de página default a página de publicidad y paso de login a pág…
> Nueva página default

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarJuridicos.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarJuridicos.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroJuridicos.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
Update de juridica falta query
> Falta update de juridica

- ProyectoASPEmenic/ProyectoASPEmenic/App_Code/Conexion.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Login.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/CrearUsuario.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/CrearUsuario.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/CrearUsuario.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
Creación de listado usuario
Pendiente:
- [ Actualizar Contraseña] 
- [ Dar de baja usuarios]
> Redireccionamiento de formulario crear persona natural a form usuario

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/ListadoClientes.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/ListadoClientes.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/ListadoClientes.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarJuridicos.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Publicidad/Index.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
crud juridicas, clientes y servicios
> Crud completo Juridicas, clientes y agregando servicios

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ListadoEmenic.aspx.cs
> Ultimos cambios

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
> Cambiando formulario

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
Ingreso del registro del cliente y listado de los que se han registrado
> Ingreso del nuevo servicio del cliente

- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
- ProyectoASPEmenic/ProyectoASPEmenic/Web.config
- ProyectoASPEmenic/ProyectoASPEmenic/css/ComboBox.css
- ProyectoASPEmenic/ProyectoASPEmenic/packages.config
Se agrega ajaxcontroltoolkit y combobox con autocomplete
> Ajaxcontroltoolkit y Combobox dinamico

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
Ingreso del servicio contratado
> Ingreso de Servicio

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/ListadoClientes.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
Actualizar servicio, problema con ddl dinamico
> Inicio de actualizar servicios

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx.designer.cs
> Cambiando las tablas de naturales y juridicas

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
Consulta de update, con error en drop dinamico (ingreso y actualizacion)
> Probando consulta de update servicio

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
Se agrega propiedad y restricciones a consignatario
> Agregar propiedad a ddlConsignatario

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ListadoEmenic.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ListadoEmenic.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
> Terminando update

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.cs
Agregando valores a variables decimales
> Seteando valores a campos decimales

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActualizarCartaPorte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActualizarCartaPorte.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActualizarCartaPorte.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/RegistroCartaporte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/RegistroCartaporte.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Transporte/Transporte.aspx
> Actualización de carta porte

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx.designer.cs
Agregando funciones javascript
> Cambiando configuracion de decimales

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActulizarContrato.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActulizarContrato.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActulizarContrato.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
- ProyectoASPEmenic/ProyectoASPEmenic/Web.config
- ProyectoASPEmenic/ProyectoASPEmenic/packages.config
Agregando funcionalidad a  contrato
> Arreglando contrato

- ProyectoASPEmenic/ProyectoASPEmenic/DSEmenic.Designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/DSEmenic.xsd
- ProyectoASPEmenic/ProyectoASPEmenic/MasterPage.Master
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Clientes/ListadoClientes.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Dashboard.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ListadoEmenic.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ActualizarNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/ListadoNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroJuridicos.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Personas/RegistroNaturales.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActualizarCartaPorte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ActulizarContrato.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ListadoContrato.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/RegistroCartaporte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/RegistroContrato.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Servicios/ServicioContratado.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Transporte/ActualizarTransporte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Transporte/ListadoTransporte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Transporte/Transporte.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ActualizarUsuario.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/CrearUsuario.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Usuarios/ListadoUsuarios.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/ReportCP.rdlc
Agregar campo a sp y cambio scripts
> Arreglar scripts

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ListadoEmenic.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
> Carga de datos emenic empresa

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx.designer.cs
> CRUD de emenic tabla 1

- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenic.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenicLogistica.aspx
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenicLogistica.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ActualizarEmenicLogistica.aspx.designer.cs
- ProyectoASPEmenic/ProyectoASPEmenic/Paginas/Emenic/ListadoEmenic.aspx.cs
- ProyectoASPEmenic/ProyectoASPEmenic/ProyectoASPEmenic.csproj
> Crud de emenic 2
